import Head from "next/head";
import Image from "next/image";
import Features from "../components/features/Features";
import Header from "../components/header/Header";
import Hero from "../components/hero-intro/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-[url('/box.svg')] bg-repeat object-fill ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/basier" rel="stylesheet" />
      </Head>
      <Header />
      <Hero />
      <Features />
    </div>
  );
}
